# Jekyll configuration for Open SDG platform
remote_theme: open-sdg/open-sdg@2.4.0

title: general.site_title
url: ""
environment: staging

languages:
  - en
  - bs
  - sr
  - hr

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

# --- TABOVI (Vizuelni prikaz) ---
indicator_tabs:
  tab_1:
    label: global_indicators.description-label
    metadata:
      - indicator_definition
  tab_2:
    label: global_indicators.intention-label
    metadata:
      - goal_meta_link_text
  tab_3:
    label: global_indicators.methodology-label
    metadata:
      - methodology_characteristics

# --- REGISTRACIJA (Dozvola za prikaz) ---
indicator_metadata:
  - name: indicator_definition
    label: global_indicators.description-label
  - name: goal_meta_link_text
    label: global_indicators.intention-label
  - name: methodology_characteristics
    label: global_indicators.methodology-label
